defmodule AshNotificationsBugRepro.Repo.Migrations.AddGarageDomainWithResources do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:doors, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :status, :text, null: false, default: "locked"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :car_id, :uuid
    end

    create table(:cars, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:doors) do
      modify :car_id,
             references(:cars,
               column: :id,
               name: "doors_car_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    alter table(:cars) do
      add :status, :text, null: false, default: "locked"

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:cars) do
      remove :updated_at
      remove :inserted_at
      remove :status
    end

    drop constraint(:doors, "doors_car_id_fkey")

    alter table(:doors) do
      modify :car_id, :uuid
    end

    drop table(:cars)

    drop table(:doors)
  end
end
